"use client";

import { useMemo, useState, useTransition } from "react";
import { CalendarDays, ChevronDown, MapPin, Plus, Printer, Trash2, Users } from "lucide-react";
import { toast } from "sonner";
import { addEventParticipant, removeEventParticipant } from "@/actions/participant";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

type EventItem = { id: string; title: string; type: string; date: Date; startTime: Date; endTime: Date; location: string; participants: Array<{ id: string; status: string; user: { id: string; username: string; firstName: string | null; lastName: string | null; email: string | null } }> };
type Guest = { id: string; username: string; firstName: string | null; lastName: string | null };
const types: Record<string, string> = { CONFERENCIA: "Conferencia", TALLER: "Taller", SIMPOSIO: "Simposio", CONGRESO: "Congreso", CAPACITACION: "Capacitación", EXPOSICION: "Exposición", RETROALIMENTACION: "Retroalimentación" };
const invitation: Record<string, { label: string; className: string }> = { ACCEPTED: { label: "Confirmado", className: "bg-emerald-500/10 text-emerald-700" }, REJECTED: { label: "Rechazado", className: "bg-red-500/10 text-red-700" }, PENDING: { label: "En espera", className: "bg-amber-500/10 text-amber-700" } };
const dateText = (value: Date) => new Intl.DateTimeFormat("es-NI", { dateStyle: "long" }).format(new Date(value));
const timeText = (value: Date) => new Intl.DateTimeFormat("es-NI", { hour: "numeric", minute: "2-digit" }).format(new Date(value));
const personName = (user: EventItem["participants"][number]["user"] | Guest) => `${user.firstName ?? ""} ${user.lastName ?? ""}`.trim() || user.username;

export function AttendanceManagement({ events, guests }: { events: EventItem[]; guests: Guest[] }) {
  const [date, setDate] = useState(""); const [type, setType] = useState(""); const [location, setLocation] = useState(""); const [opened, setOpened] = useState<string | null>(events[0]?.id ?? null); const [selected, setSelected] = useState<Record<string, string>>({});
  const [pending, startTransition] = useTransition();
  const filtered = useMemo(() => events.filter(event => (!date || new Date(event.date).toISOString().slice(0, 10) === date) && (!type || event.type === type) && (!location || event.location.toLowerCase().includes(location.toLowerCase()))), [events, date, type, location]);
  const clear = () => { setDate(""); setType(""); setLocation(""); };
  const run = (work: () => Promise<unknown>, success: string) => startTransition(async () => { try { await work(); toast.success(success); } catch (error) { toast.error(error instanceof Error ? error.message : "No se pudo completar la operación"); } });

  return <main className="attendance-report mx-auto max-w-6xl space-y-6 p-6 md:p-8">
    <style>{`@media print { body * { visibility: hidden; } .attendance-report, .attendance-report * { visibility: visible; } .attendance-report { position: absolute; left: 0; top: 0; width: 100%; max-width: none; padding: 24px; } .print-hidden { display: none !important; } .print-event { break-inside: avoid; border: 1px solid #bbb; margin-bottom: 16px; } }`}</style>
    <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><h1 className="text-3xl font-bold tracking-tight">Asistencia</h1><p className="mt-1 text-muted-foreground">Administra invitados y consulta el estado de cada invitación.</p></div><Button className="print-hidden" variant="outline" onClick={() => window.print()}><Printer className="mr-2 h-4 w-4" />Imprimir asistencia</Button></header>
    <Card className="print-hidden"><CardContent className="grid gap-3 p-5 md:grid-cols-4"><Input type="date" aria-label="Fecha del evento" value={date} onChange={e => setDate(e.target.value)} /><select aria-label="Tipo de evento" value={type} onChange={e => setType(e.target.value)} className="h-10 rounded-md border bg-background px-3 text-sm"><option value="">Todos los tipos</option>{Object.entries(types).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><Input value={location} onChange={e => setLocation(e.target.value)} placeholder="Buscar por lugar" aria-label="Lugar" /><Button variant="outline" onClick={clear}>Limpiar filtros</Button></CardContent></Card>
    <p className="print-hidden text-sm text-muted-foreground">{filtered.length} {filtered.length === 1 ? "evento encontrado" : "eventos encontrados"}</p>
    <section className="space-y-4">{filtered.length === 0 ? <Card><CardContent className="p-12 text-center text-muted-foreground">No hay eventos que coincidan con los filtros.</CardContent></Card> : filtered.map(event => {
      const confirmed = event.participants.filter(p => p.status === "ACCEPTED").length; const isOpen = opened === event.id; const available = guests.filter(guest => !event.participants.some(participant => participant.user.id === guest.id));
      return <Card key={event.id} className="print-event overflow-hidden"><CardHeader className="cursor-pointer p-5" onClick={() => setOpened(isOpen ? null : event.id)}><div className="flex justify-between gap-4"><div className="space-y-2"><CardTitle className="text-xl">{event.title}</CardTitle><div className="flex flex-wrap gap-x-4 gap-y-1 text-sm text-muted-foreground"><span className="flex items-center gap-1"><CalendarDays className="h-4 w-4" />{dateText(event.date)} · {timeText(event.startTime)} – {timeText(event.endTime)}</span><span className="flex items-center gap-1"><MapPin className="h-4 w-4" />{event.location}</span><span>{types[event.type]}</span></div></div><ChevronDown className={`print-hidden h-5 w-5 transition-transform ${isOpen ? "rotate-180" : ""}`} /></div></CardHeader>
      <CardContent className={`${isOpen ? "block" : "hidden print:block"} border-t p-0`}><div className="print-hidden flex flex-col gap-3 border-b p-4 sm:flex-row"><select value={selected[event.id] ?? ""} onChange={e => setSelected(value => ({ ...value, [event.id]: e.target.value }))} className="h-10 flex-1 rounded-md border bg-background px-3 text-sm"><option value="">Selecciona un invitado para agregar</option>{available.map(guest => <option key={guest.id} value={guest.id}>{personName(guest)} · {guest.username}</option>)}</select><Button disabled={pending || !selected[event.id]} onClick={() => run(() => addEventParticipant(event.id, selected[event.id]), "Invitado agregado; su invitación queda en espera")}><Plus className="mr-1 h-4 w-4" />Agregar</Button></div>
      {event.participants.length === 0 ? <p className="p-5 text-sm text-muted-foreground">Todavía no hay invitados para este evento.</p> : <div className="overflow-x-auto"><table className="w-full min-w-[600px] text-sm"><thead className="border-b bg-muted/30 text-left text-muted-foreground"><tr><th className="p-4 font-medium">Participante</th><th className="p-4 font-medium">Correo electrónico</th><th className="p-4 font-medium">Estado de invitación</th><th className="print-hidden p-4 text-right font-medium">Acción</th></tr></thead><tbody>{event.participants.map(participant => { const state = invitation[participant.status]; return <tr key={participant.id} className="border-b last:border-0"><td className="p-4 font-medium">{personName(participant.user)}</td><td className="p-4 text-muted-foreground">{participant.user.email || participant.user.username}</td><td className="p-4"><span className={`rounded-full px-2 py-1 text-xs ${state.className}`}>{state.label}</span></td><td className="print-hidden p-4 text-right"><Button size="icon" variant="ghost" disabled={pending} aria-label={`Eliminar a ${personName(participant.user)}`} onClick={() => { if (window.confirm(`¿Retirar a ${personName(participant.user)} de la lista?`)) run(() => removeEventParticipant(participant.id), "Invitado retirado de la lista"); }}><Trash2 className="h-4 w-4 text-destructive" /></Button></td></tr>; })}</tbody></table></div>}<footer className="flex items-center gap-2 border-t bg-muted/20 px-5 py-4 text-sm font-medium"><Users className="h-4 w-4" />Asistentes confirmados: {confirmed} de {event.participants.length} invitados.</footer></CardContent></Card>;
    })}</section>
  </main>;
}
