-- AlterTable
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "ingressId" TEXT;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "serverUrl" TEXT;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "streamKey" TEXT;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "obsConnected" BOOLEAN NOT NULL DEFAULT false;

CREATE UNIQUE INDEX IF NOT EXISTS "Event_ingressId_key" ON "Event"("ingressId");
